### ISSUE TITLE
Duration of generated audio

### ISSUE THREAD

**Issue by sakshamsingh1** [naver-ai/rewas#4]
Hi,
Thanks for open-sourcing your wonderful work. 

- Compared to most visual-to-audio models that generate and evaluate on 10-second samples, the REWAS model produces audio with a duration of 5 seconds. I was wondering if you could explain why the duration is 5 seconds.

- Additionally, I’m interested in extending the audio duration to 10 seconds. Would adjusting the shape of the initial noise latent be sufficient to achieve this, or would I need to generate two 5-second segments and combine them?

Thanks

**Comment by eugene6923** [comment]
Hi, thank you for your interest in our work.

We initially considered generating 10-second audio samples, similar to other models. However, since our control prediction model, based on Synchformer, was trained on 4.8-second clips (approximately 5 seconds), we decided to use 5-second samples instead. That said, if you train the Energy Adapter (ControlNet in AudioLDM) using 10-second samples—which is neither difficult nor time-consuming (it only requires adjusting the shape of the initial noise, as you mentioned)—you could concatenate two outputs from our control prediction model and use them in your retrained Energy Adapter. I recommend retraining the Energy Adapter for 10-second samples rather than summing two 5 second segments or changing the shape of initial noise.
